### ISSUE TITLE
Two input files to model are missing

### ISSUE THREAD

**Issue by adamwoolfe** [jostmey/MaxSnippetModelOvarian#1]
Hi, cool method.

The program requires two files that are not included in the repository 
/dataset/database.h5
/lib/atchley.csv

Could you add these to the repository please. Thank you.

**Comment by jostmey** [comment]
I apologize for the delay in fixing these issues!

I have added "/lib/atchley.csv" to the repo, which was missing.

To rebuild '/dataset/database.h5', navigate to 'dataset/downloads', run 'python3 download_ovarian_data.py', then navigate to '/dataset', and finally run 'python3 prepare_data_20180417.py' and 'python3 prepare_data_20181218.py'. That should produce 'database.h5'
